"""Abstract base class for LLM providers."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any

from pawnlogic.core.message import Message


@dataclass
class LLMResponse:
    """A response returned by an LLM provider.

    Attributes:
        content: The text generated by the model.
        model: Model identifier reported by the provider.
        usage: Token-usage statistics (provider-specific keys).
        raw: The raw response object from the provider SDK, if available.
    """

    content: str
    model: str
    usage: dict[str, int] = field(default_factory=dict)
    raw: Any = field(default=None, repr=False)


class LLMProvider(ABC):
    """Abstract base class that every LLM provider must implement.

    Subclasses only need to implement :meth:`complete` (and optionally
    :meth:`complete_async` for asynchronous use).
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """Human-readable provider name (e.g. ``"openai"``)."""

    @abstractmethod
    def complete(
        self,
        messages: list[Message],
        *,
        model: str,
        temperature: float = 0.7,
        max_tokens: int | None = None,
        **kwargs: Any,
    ) -> LLMResponse:
        """Send *messages* to the model and return a response.

        Args:
            messages: Ordered conversation history to send to the model.
            model: Model identifier (e.g. ``"gpt-4o"``).
            temperature: Sampling temperature in ``[0, 2]``.
            max_tokens: Upper bound on generated tokens. ``None`` means
                the provider default.
            **kwargs: Provider-specific keyword arguments.

        Returns:
            The model's reply wrapped in an :class:`LLMResponse`.
        """

    async def complete_async(
        self,
        messages: list[Message],
        *,
        model: str,
        temperature: float = 0.7,
        max_tokens: int | None = None,
        **kwargs: Any,
    ) -> LLMResponse:
        """Async variant of :meth:`complete`.

        The default implementation runs :meth:`complete` in a thread pool
        so that concrete providers only need to implement the synchronous
        method.  Override this method to use a native async SDK.
        """
        import asyncio

        loop = asyncio.get_running_loop()
        return await loop.run_in_executor(
            None,
            lambda: self.complete(
                messages,
                model=model,
                temperature=temperature,
                max_tokens=max_tokens,
                **kwargs,
            ),
        )
